routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/', 'IndexController@index')->name('index');
Route::get('/home', 'HomeController@index')->name('dashboard');
Route::resource('blog', 'BlogController');
Route::get('userBlog', 'BlogController@userBlog')->name('userBlog');
Route::get('userProduct', 'ProductController@userProduct')->name('userProduct');
Route::resource('/product', 'ProductController');
Route::get('/about', function () {
   return view('about');
});
Route::get('/contact', function () {
    return view('contact');
 });
Route::post('contact', 'ContactController@sendMsg')->name('contact');
Route::post('/subscribe', 'SubscribeController@subscribe')->name('subscribe');
Route::resource('cart', 'CartController');
Route::resource('order', 'OrderController');

resources/views/about.blade.php
@extends('layouts.app')

@section('content')
<div class="slide-page w-100" style="background-image: url('{{ asset('img/slide/slide1.jpg') }}')">
    <div class="container">
        <h1 class="text-center color-1">About Us</h1>
    </div>
</div>
<div class="container my-5">
    <div class="row">
        <div class="col-lg-6 col-12"><img src="{{ asset('img/sq-1.jpg') }}" alt="" class="w-100"></div>
        <div class="col-lg-6 col-12"><h3 class="my-5">Who Are We!!</h3>
        <p>In 1996, Magnolia Bakery opened its first location on a quiet street corner in the heart of New York City’s West Village. From its inception, Magnolia Bakery has been cherished for its classic American baked goods, vintage decor and warm, inviting atmosphere.
            In 2007, Magnolia Bakery’s original owner passed her oven mitts to Steve and Tyra Abrams. Together, the Abrams’ have thoughtfully expanded the bakery from its first West Village shop to locations worldwide. Today, Magnolia Bakery can be found in New York City, Los Angeles, Chicago, Boston, Washington, D.C., Dubai, Riyadh, Amman, Abu Dhabi, Manila and Doha. For more information on Magnolia Bakery’s location</p>
        </div>
    </div>
</div>
@endsection

resources/views/blog.blade.php
@extends('layouts.app')

@section('content')
<div class="slide-page w-100" style="background-image: url('{{ asset('img/slide/slide1.jpg') }}')">
    <div class="container">
        <h1 class="text-center color-1">Blog</h1>
    </div>
</div>
<div class="container blogs my-5">
    <div class="row">
        @forelse ($posts as $post)
            <div class="col-12 col-lg-4 mb-3">
                <div class="card w-100">
                    <img src="{{asset('img/upload/blog/' .  $post->img)}}" class="card-img-top w-100" alt="..." height="250">
                    <div class="card-body">
                      <h5 class="card-title">{{ $post->title}}</h5>
                      <p class="card-text">{{ $post->des}} ...</p>
                      <a href="{{route('blog.show',$post->id)}}" class="btn btn-primary w-100 bg-1 border-color-1">Read More ...</a>
                    </div>
                  </div>
            </div>
        @empty
            There is now Posts
        @endforelse
    </div>
</div>
@endsection

resources/views/cart.blade.php
@extends('layouts.app')
@section('content')
<div class="slide-page w-100" style="background-image: url('{{ asset('img/slide/slide1.jpg') }}')">
    <div class="container">
        <h1 class="text-center color-1">Shopping Cart</h1>
    </div>
</div>

    <div class="container my-5">
        <h2>Your cart Products ({{ Cart::count()}})</h2>   
        <div class="row text-center mt-3 bg-1 py-4 color-4">
            <div class="col-4">Product Name</div>
            <div class="col-2">Product Price</div>
            <div class="col-2">Quantity</div>
            <div class="col-2">Total Price</div>
            <div class="col-2"></div>
        </div> 
            @forelse (Cart::content() as $item)
            <div class="row text-center bg-4 py-4 color-1">
                <a class="col-4 mt-2" href="{{route('product.show',$item->id)}}">{{ $item->name}}</a>
                <div class="col-2 mt-2">{{ $item->price}}</div>
                <div class="col-2 mt-2">{{ $item->qty}}</div>
                <div class="col-2 mt-2">{{ $item->subtotal}}</div>
                <div class="col-2 mt-2">                                            
                    <form action="{{ route('cart.destroy', $item->rowId)}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn-delete" title="Remove Product" type="submit">
                        <i class="fa fa-trash"></i>
                    </button>
                    </form>
                </div>
            </div> 
            @empty
                <h3 class="color-red text-center w-100 mt-4">There is no products in the cart</h3>
            @endforelse
            <h5 class="col-6 color-1 mt-4">Total Price ({{ Cart::SubTotal()}})</h5>
            @auth    
            <form action="{{ route('order.store')}}" method="post">
                @csrf
                    <button class="btn bg-2 color-4" title="Send Order" type="submit">
                        Send Order
                    </button>
            </form>
            @else
                <h3 class="color-red text-center w-100 my-5">You have to login to add your order</h3>
            @endauth
    </div>
      
    <script>
        function changeQty(increase) {
            var qty = parseInt($('.select_number').find("input").val());
            if (!isNaN(qty)) {
                qty = increase ? qty + 1 : (qty > 1 ? qty - 1 : 1);
                $('.select_number').find("input").val(qty);
            } else {
                $('.select_number').find("input").val(1);
            }
        }

        function goToByScroll(id) {
            $('html,body').animate({
                scrollTop: $("#" + id).offset().top
            }, 'slow');
        }
    </script>
@endsection

resources/views/editBlog.blade.php
@extends('layouts.app')

@section('content')
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Post</div>

                <div class="card-body">
                    <img src="{{asset('img/upload/blog/' .  $blog->img)}}" alt="...." class="w-100" height="500">
                    <form method="POST" action="{{ route('blog.update', $blog->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                          <label for="title">Title</label>
                        <input type="text" value="{{$blog->title}}" class="form-control" name="title" id="title" aria-describedby="titleHelp" autocomplete="off" required>
                          <small id="titleHelp" class="form-text text-muted">Enter The Title of The Post</small>
                        </div>
                        <div class="form-group">
                            <label for="description">Description</label>
                            <input type="text" value="{{$blog->des}}" class="form-control" id="description" name="description" aria-describedby="descriptionHelp" autocomplete="off" required>
                            <small id="description" class="form-text text-muted">Enter The description of The Post</small>
                        </div>
                        <div class="form-group">
                            <label for="content">Content</label>
                            <input type="hidden" value="{{$blog->content}}" name="content" class="form-control" id="content" aria-describedby="contentHelp" autocomplete="off" required >
                            <trix-editor input="content"></trix-editor>
                            <small id="content" class="form-text text-muted">Enter The Content of The Post</small>
                        </div>
                        <button type="submit" class="btn bg-1 color-4 w-100">Edit Post</button>
                      </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <a href="{{route('product.create')}}" class="btn w-100 color-4 bg-1 border-color-1">Add Product</a>
                        </div>
                        <div class="col-12 mt-2">
                            <a href="{{route('blog.create')}}" class="btn w-100 color-4 bg-2 border-color-2">Add Post</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
    @yield('index.slide', View::make('index.slide'))
    <div class="container product-list mb-5 mt-5">
        <h2 class="title main-font-bold color-1">Hot Product</h2>
        <!-- Set up your HTML -->
        <div class="owl-carousel my-5">
            @forelse ($products1 as $item)
                <div class="item position-relative">
                    <img src="{{asset('img/upload/product/' .  $item->img1)}}" alt="{{$item->name}}" class="w-100 h-100 position-relative">
                    <div class="content position-absolute pt-5 text-center color-1">
                        <h4 class="mt-3">{{$item->name}}</h4>
                        <h5>${{$item->price}}</h5>
                        <div class="row">
                            <div class="col-6">
                                <a href="{{route('product.show',$item->id)}}" class="color-red tool fa fa-eye font-big" title="Show"></a>
                            </div>
                            <div class="col-6">
                                <form method="post" action="{{ route('cart.store')}}">
                                    {{ csrf_field() }}
                                    <input name="id" type="hidden" value="{{$item->id}}">
                                    <input name="name" type="hidden" value="{{$item->name}}">
                                    <input name="qty" value="1" type="hidden" value="{{$item->qty}}">
                                    <input name="price" type="hidden" value="{{$item->price}}">
                                    <button class="color-red tool btn fa fa-cart-plus font-big p-0" title="Add To Cart" type="submit">
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
            No Prodects
            @endforelse
        </div>
    </div>
    <div class="container product-list mb-5 mt-5">
        <h2 class="title main-font-bold color-1">Cakes</h2>
        <!-- Set up your HTML -->
        <div class="owl-carousel my-5">
            @forelse ($cakes as $item)
                <div class="item position-relative">
                    <img src="{{asset('img/upload/product/' .  $item->img1)}}" alt="{{$item->name}}" class="w-100 h-100 position-relative">
                    <div class="content position-absolute pt-5 text-center color-1">
                        <h4 class="mt-3">{{$item->name}}</h4>
                        <h5>${{$item->price}}</h5>
                        <div class="row">
                            <div class="col-6">
                                <a href="{{route('product.show',$item->id)}}" class="color-red tool fa fa-eye font-big" title="Show"></a>
                            </div>
                            <div class="col-6">
                                <form method="post" action="{{ route('cart.store')}}">
                                    {{ csrf_field() }}
                                    <input name="id" type="hidden" value="{{$item->id}}">
                                    <input name="name" type="hidden" value="{{$item->name}}">
                                    <input name="qty" value="1" type="hidden" value="{{$item->qty}}">
                                    <input name="price" type="hidden" value="{{$item->price}}">
                                    <button class="color-red tool btn fa fa-cart-plus font-big p-0" title="Add To Cart" type="submit">
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
            No Cake Prodects
            @endforelse
        </div>
    </div>
    <div class="container product-list mb-5 mt-5">
        <h2 class="title main-font-bold color-1">Breads</h2>
        <!-- Set up your HTML -->
        <div class="owl-carousel my-5">
            @forelse ($breads as $item)
                <div class="item position-relative">
                    <img src="{{asset('img/upload/product/' .  $item->img1)}}" alt="{{$item->name}}" class="w-100 h-100 position-relative">
                    <div class="content position-absolute pt-5 text-center color-1">
                        <h4 class="mt-3">{{$item->name}}</h4>
                        <h5>${{$item->price}}</h5>
                        <div class="row">
                            <div class="col-6">
                                <a href="{{route('product.show',$item->id)}}" class="color-red tool fa fa-eye font-big" title="Show"></a>
                            </div>
                            <div class="col-6">
                                <form method="post" action="{{ route('cart.store')}}">
                                    {{ csrf_field() }}
                                    <input name="id" type="hidden" value="{{$item->id}}">
                                    <input name="name" type="hidden" value="{{$item->name}}">
                                    <input name="qty" value="1" type="hidden" value="{{$item->qty}}">
                                    <input name="price" type="hidden" value="{{$item->price}}">
                                    <button class="color-red tool btn fa fa-cart-plus font-big p-0" title="Add To Cart" type="submit">
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
            No Breads Prodects
            @endforelse
        </div>
    </div>
    <div class="container product-list mb-5 mt-5">
        <h2 class="title main-font-bold color-1">Pies</h2>
        <!-- Set up your HTML -->
        <div class="owl-carousel my-5">
            @forelse ($pies as $item)
                <div class="item position-relative">
                    <img src="{{asset('img/upload/product/' .  $item->img1)}}" alt="{{$item->name}}" class="w-100 h-100 position-relative">
                    <div class="content position-absolute pt-5 text-center color-1">
                        <h4 class="mt-3">{{$item->name}}</h4>
                        <h5>${{$item->price}}</h5>
                        <div class="row">
                            <div class="col-6">
                                <a href="{{route('product.show',$item->id)}}" class="color-red tool fa fa-eye font-big" title="Show"></a>
                            </div>
                            <div class="col-6">
                                <form method="post" action="{{ route('cart.store')}}">
                                    {{ csrf_field() }}
                                    <input name="id" type="hidden" value="{{$item->id}}">
                                    <input name="name" type="hidden" value="{{$item->name}}">
                                    <input name="qty" value="1" type="hidden" value="{{$item->qty}}">
                                    <input name="price" type="hidden" value="{{$item->price}}">
                                    <button class="color-red tool btn fa fa-cart-plus font-big p-0" title="Add To Cart" type="submit">
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
            No Breads Prodects
            @endforelse
        </div>
    </div>
    <div class="container product-list mb-5 mt-5">
        <h2 class="title main-font-bold color-1">Blogs</h2>
        <!-- Set up your HTML -->
        <div class="owl-carousel">
            @forelse ($blog as $item)
                <div class="item position-relative">
                    <img src="{{asset('img/upload/blog/' .  $item->img)}}" alt="{{$item->title}}" class="w-100 h-100 position-relative">
                    <div class="content position-absolute pt-5 text-center color-1">
                        <h4 class="mt-3">{{$item->title}}</h4>
                        <a href="{{route('blog.show',$item->id)}}" class="btn color-red bg-4">Read More ...</a>
                    </div>
                </div>
            @empty
            No Blog
            @endforelse
        </div>
    </div>
@endsection
    

resources/views/product.blade.php
@extends('layouts.app')

@section('content')
<div class="slide-page w-100" style="background-image: url('{{ asset('img/slide/slide1.jpg') }}')">
    <div class="container">
        <h1 class="text-center color-1">Products</h1>
    </div>
</div>
<div class="container blogs my-5">
    <div class="row product-list">
        @forelse ($product as $product)
            <div class="col-12 col-lg-4 mb-3">
                <div class="item position-relative" style="">
                    <img src="{{asset('img/upload/product/' .  $product->img1)}}" alt="{{$product->name}}" class="w-100 h-100 position-relative">
                    <div class="content position-absolute py-5 text-center color-1">
                        <h4 class="mt-2">{{$product->name}}</h4>
                        <h5>{{$product->price}}</h5>
                        <div class="row">
                            <div class="col-6">
                                <a href="{{route('product.show',$product->id)}}" class="color-red tool fa fa-eye font-big" title="Show"></a>
                            </div>
                            <div class="col-6">
                                <form method="post" action="{{ route('cart.store')}}">
                                    {{ csrf_field() }}
                                    <input name="id" type="hidden" value="{{$product->id}}">
                                    <input name="name" type="hidden" value="{{$product->name}}">
                                    <input name="qty" value="1" type="hidden" value="{{$product->qty}}">
                                    <input name="price" type="hidden" value="{{$product->price}}">
                                    <button class="color-red tool btn fa fa-cart-plus font-big p-0" title="Add To Cart" type="submit">
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @empty
            There is now products
        @endforelse
    </div>
</div>
@endsection

resources/views/singleBlog.blade.php
@extends('layouts.app')

@section('content')
<div class="container my-5">
    <div class="row">
        <div class="col-12 mb-3">
            <h1>{{$post->title}}</h1>
        </div>
        <div class="col-12">
            <img src="{{asset('img/upload/blog/' .  $post->img)}}" alt="...." class="w-100" height="700">
        </div>
        <div class="col-12 mt-3">
            {!!$post->content!!}
        </div>

    </div>

    <div class="container product-list mb-5 mt-5">
        <h2 class="title main-font-bold color-1">Hot Products</h2>
        <!-- Set up your HTML -->
        <div class="owl-carousel">
            @forelse ($products as $item)
                <div class="item position-relative">
                    <img src="{{asset('img/upload/product/' .  $item->img1)}}" alt="{{$item->name}}" class="w-100 h-100 position-relative">
                    <div class="content position-absolute pt-5 text-center color-1">
                        <h4 class="mt-3">{{$item->name}}</h4>
                        <h5>{{$item->price}}</h5>
                        <div class="row">
                            <div class="col-6">
                                <a href="{{route('product.show',$item->id)}}" class="color-red tool fa fa-eye font-big" title="Show"></a>
                            </div>
                            <div class="col-6">
                                <form method="post" action="{{ route('cart.store')}}">
                                    {{ csrf_field() }}
                                    <input name="id" type="hidden" value="{{$item->id}}">
                                    <input name="name" type="hidden" value="{{$item->name}}">
                                    <input name="qty" value="1" type="hidden" value="{{$item->qty}}">
                                    <input name="price" type="hidden" value="{{$item->price}}">
                                    <button class="color-red tool btn fa fa-cart-plus font-big p-0" title="Add To Cart" type="submit">
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
            No Prodects
            @endforelse
        </div>
    </div>
    <div class="container product-list mb-5 mt-5">
        <h2 class="title main-font-bold color-1">Blogs</h2>
        <!-- Set up your HTML -->
        <div class="owl-carousel">
            @forelse ($alsoBlog as $item)
                <div class="item position-relative">
                    <img src="{{asset('img/upload/blog/' .  $item->img)}}" alt="{{$item->title}}" class="w-100 h-100 position-relative">
                    <div class="content position-absolute pt-5 text-center color-1">
                        <h4 class="mt-3">{{$item->title}}</h4>
                        <a href="{{route('blog.show',$item->id)}}" class="btn color-red bg-4">Read More ...</a>
                    </div>
                </div>
            @empty
            No Blog
            @endforelse
        </div>
    </div>
</div>
@endsection

resources/views/singleProduct.blade.php
@extends('layouts.app')

@section('content')
<div class="container my-5">
    <div class="row">
        <div class="col-12 col-md-6">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{{asset('img/upload/product/' .  $product->img1)}}" alt="{{$product->name}}" class="w-100" height="500">
                  </div>
                  <div class="carousel-item">
                    <img src="{{asset('img/upload/product/' .  $product->img2)}}" alt="{{$product->name}}" class="w-100" height="500">
                  </div>
                  <div class="carousel-item">
                    <img src="{{asset('img/upload/product/' .  $product->img3)}}" alt="{{$product->name}}" class="w-100" height="500">
                  </div>
                </div>
                <a class="carousel-control-prev " href="#carouselExampleControls" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon bg-1 color-1" aria-hidden="true"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next " href="#carouselExampleControls" role="button" data-slide="next">
                  <span class="carousel-control-next-icon bg-1 color-1" aria-hidden="true"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
        </div>
        <div class="col-12 col-md-6">
            <h1>{{$product->name}}</h1>
            <h3 class="my-5 color-1">Price : {{$product->price}}$<h3>
            <div class="col-6">
                <form method="post" action="{{ route('cart.store')}}">
                    {{ csrf_field() }}
                    <input name="id" type="hidden" value="{{$product->id}}">
                    <input name="name" type="hidden" value="{{$product->name}}">
                    <input name="price" type="hidden" value="{{$product->price}}">
                    <div class="row">
                        <div class="col-6"><input name="qty" value="1" type="number" value="{{$product->qty}}" class="form-control"></div>
                        <div class="col-6"><button class="color-red tool btn fa fa-cart-plus font-big p-0 m-0" title="Add To Cart" type="submit">
                        </button></div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="container product-list mb-5 mt-5">
        <h2 class="title main-font-bold color-1">Hot Products</h2>
        <!-- Set up your HTML -->
        <div class="owl-carousel">
            @forelse ($alsoProducts as $item)
                <div class="item position-relative">
                    <img src="{{asset('img/upload/product/' .  $item->img1)}}" alt="{{$item->name}}" class="w-100 h-100 position-relative">
                    <div class="content position-absolute pt-5 text-center color-1">
                        <h4 class="mt-3">{{$item->name}}</h4>
                        <h5>${{$item->price}}</h5>
                        <div class="row">
                            <div class="col-6">
                                <a href="{{route('product.show',$item->id)}}" class="color-red tool fa fa-eye font-big" title="Show"></a>
                            </div>
                            <div class="col-6">
                                <a href="#" class="color-red tool fa fa-cart-plus font-big" title="Add To Cart"></a>
                            </div>
                        </div>
                    </div>
                </div>
            @empty
            No Prodects
            @endforelse
        </div>
    </div>
    <div class="container product-list mb-5 mt-5">
        <h2 class="title main-font-bold color-1">Blogs</h2>
        <!-- Set up your HTML -->
        <div class="owl-carousel">
            @forelse ($blogs as $item)
                <div class="item position-relative">
                    <img src="{{asset('img/upload/blog/' .  $item->img)}}" alt="" class="w-100 h-100 position-relative">
                    <div class="content position-absolute pt-5 text-center color-1">
                        <h4 class="mt-3">{{$item->title}}</h4>
                        <a href="{{route('blog.show',$item->id)}}" class="btn color-red bg-4">Read More ...</a>
                    </div>
                </div>
            @empty
            No Blog
            @endforelse
        </div>
    </div>
</div>
@endsection

resources/views/userBlog.blade.php
@extends('layouts.app')

@section('content')
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    <h2 class="mb-3">Your Blog Posts</h2>
                    @forelse ($posts as $post)
                        <div class="row py-3">
                            <div class="col-9">
                                <a href="{{route('blog.show',$post->id)}}" class="color-1">{{$post->title}}</a>
                            </div>
                            <div class="col-1">
                                <a href="{{route('blog.show',$post->id)}}" class="color-1 tool" title="Show"><i class="fa fa-eye" aria-hidden="true"></i></a>
                            </div>
                            <div class="col-1">
                                <a href="{{route('blog.edit',$post->id)}}" class="color-2 tool" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                            </div>
                            <div class="col-1">
                                <a href="#"class="color-red  tool" data-toggle="modal" data-target="#Modal{{$post->id}}" title="Delete"><i class="fa fa-times" aria-hidden="true"></i></a>
                            </div>
                        </div>
                        <!-- Pop-up Modal -->
                        <div class="modal fade" id="Modal{{$post->id}}" tabindex="-1" role="dialog" aria-labelledby="Modal{{$post->id}}Label" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Delete Post</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                    Delete {{$post->title}}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <form action="{{route('blog.destroy',$post->id)}}" method="post">
                                        @method('delete')
                                        @csrf
                                        <input class="btn color-4 bg-1" type="submit" value="Delete" />
                                    </form>

                                </div>
                            </div>
                            </div>
                        </div>
                    @empty
                        You Have No Posts
                    @endforelse
                    <div class="col-12 mt-5 mb-3">
                        <a href="{{route('blog.create')}}" class="btn w-100 color-4 bg-1 border-color-1">Add Post</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection